name: Build and Publish .exe

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
        arch:
          - x86_64
          - arm
        include:
          - target: x86_64-pc-windows-msvc
            arch: x86_64
          - target: aarch64-pc-windows-msvc
            arch: arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release

      - name: Rename .exe file
        run: |
          ren target\release\radio-ctl.exe radio-ctl-${{ matrix.arch }}.exe

      - name: Upload Binary to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/radio-ctl-${{ matrix.arch }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
