name: Build and Publish .exe

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-x86_64:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust for x86_64
      - name: Set up Rust for x86_64
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      # Step 3: Build the project for x86_64
      - name: Build x86_64
        run: cargo build --release

      # Step 4: Upload the x86_64 artifact
      - name: Upload x86_64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: radio-ctl-x86_64.exe
          path: target/release/radio-ctl.exe

  build-arm:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust for ARM
      - name: Set up Rust for ARM
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-pc-windows-msvc

      # Step 3: Build the project for ARM
      - name: Build ARM
        run: cargo build --release

      # Step 4: Upload the ARM artifact
      - name: Upload ARM artifact
        uses: actions/upload-artifact@v3
        with:
          name: radio-ctl-arm.exe
          path: target/release/radio-ctl.exe

  publish:
    runs-on: windows-latest
    needs: [build-x86_64, build-arm]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload x86_64 Binary to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/radio-ctl-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ARM Binary to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/radio-ctl-arm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
